spring:
  data:
    mongodb:
      uri: mongodb+srv://khushiagnihotri16:Z8yZCDEZ4W2tFLdB@cluster0.vpifjag.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: email@gmail.com
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8081
  servlet:
    context-path: /dev-journal
# logging:
#   level:
#     net.engineeringdigest.journalApp.service.JournalEntryService: trace
# logging:
#   level:
#     root: trace
weather:
  api:
    key: a4b8706c6f8bf4f3b2ee17f89b2c45f1

